### ISSUE TITLE
Reference Literature

### ISSUE THREAD

**Issue by oiao** [tovrstra/optdesign-tutorial#1]
Hi Toon,

I was wondering if you could provide some references for the tutorial. Would be nice for reading up a couple of things.

Thanks a lot,
Leo

**Comment by tovrstra** [comment]
The Max Vol algorithm is used in the following paper as a query strategy in active learning: https://doi.org/10.1016/j.commatsci.2017.08.031 with reference to a more mathematical paper here: https://doi.org/10.1142/9789812836021_0015

For more conventional D-optimality methods, which are not so useful for us, the documentation of SAS contains a good list of literature references: https://documentation.sas.com/doc/en/qcug/15.2/qcug_optex_details23.htm
The following paper reviews the basics: https://doi.org/10.1016/0167-9473(92)90064-M

**Comment by oiao** [comment]
thanks
